// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKWY-t76qpxRyKwzgq4ggStBJu888lQY',
    appId: '1:380404236034:web:12ba42d614fa575a698c1b',
    messagingSenderId: '380404236034',
    projectId: 'ostad-121b3',
    authDomain: 'ostad-121b3.firebaseapp.com',
    storageBucket: 'ostad-121b3.firebasestorage.app',
    measurementId: 'G-8F04C0CBDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrW9srxTc08HY7WG8LC2_qt2m1M36I6MU',
    appId: '1:380404236034:android:3981769978adf0a5698c1b',
    messagingSenderId: '380404236034',
    projectId: 'ostad-121b3',
    storageBucket: 'ostad-121b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZ0T2FroHRtvbILgsAEG4uCDzCY0cc9M',
    appId: '1:380404236034:ios:1b4bfb8ab714cf59698c1b',
    messagingSenderId: '380404236034',
    projectId: 'ostad-121b3',
    storageBucket: 'ostad-121b3.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZ0T2FroHRtvbILgsAEG4uCDzCY0cc9M',
    appId: '1:380404236034:ios:1b4bfb8ab714cf59698c1b',
    messagingSenderId: '380404236034',
    projectId: 'ostad-121b3',
    storageBucket: 'ostad-121b3.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );
}
